### ISSUE TITLE
Installing on VestaCP

### ISSUE THREAD

**Issue by cameronmotes** [vityabond/hopebilling#33]
After connecting to DB on stage 4 I get the following errors

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 

1067 Invalid default value for 'date' in /home/admin/web/%domain%/public_html/core/classes/System/Db/Schema/Table.php:117 Stack trace: 

#0 /home/admin/web/%domain%/public_html/core/classes/System/Db/Schema/Table.php(117): PDOStatement->execute() 

#1 /home/admin/web/%domain%/public_html/core/classes/System/Db/Schema/Schema.php(20): System\Db\Schema\Table->create() 

#2 /home/admin/web/%domain%/public_html/app/controllers/InstallController.php(211): System\Db\Schema\Schema::create('hosting_account...', Object(Closure)) 

#3 /home/admin/web/%domain%/public_html/app/controllers/InstallController.php(46): InstallController->actionDb() 

#4 /home/admin/web/%domain%/public_html/core/classes/System/Router.php(148): InstallController->run('actionIndex', Array, 'install') 

#5 /home/admin/web/%domain%/public_html/index.php(7): System\Router->run( in /home/admin/web/%domain%/public_html/core/classes/System/Db/Schema/Table.php on line 117

**Comment by BunkDev5674** [comment]
same and no1 helping its annoying af

**Comment by BunkDev5674** [comment]
[https://www.knowledgebase-script.com/kb/article/how-do-i-disable-strict-mode-in-mysql-163.html](url)

**Comment by BunkDev5674** [comment]
try that
